# Generated by Django 3.2.15 on 2022-11-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20221113_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
