# Generated by Django 3.2.15 on 2022-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Health'), (1, 'Diet'), (2, 'Exercice'), (3, 'Mind')], default=0),
        ),
    ]
