# Generated by Django 3.2.15 on 2022-10-18 18:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221008_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('Health', 'Health'), ('Diet', 'Diet'), ('Exercise', 'Exercise'), ('Relaxation', 'Relaxation')], max_length=50),
        ),
    ]
