# Generated by Django 3.2.15 on 2022-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Diet', 'Diet'), ('Exercise', 'Exercise'), ('Relaxation', 'Relaxation')], max_length=50),
        ),
    ]
