# Generated by Django 3.2.15 on 2022-11-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221121_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
