# Generated by Django 3.2.15 on 2022-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_image_recipe_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.TextField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.TextField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.TextField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Soup/Salad', 'Soup/Salad')]),
        ),
    ]
