# Generated by Django 3.2.15 on 2022-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221026_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='recipe', max_length=200),
        ),
    ]
